import { randomBytes } from 'node:crypto';
import { z } from 'zod';
import type { Application } from '@nexpanel/database';
import type { AppRuntimeSpec, ProvisionStep } from '@nexpanel/shared';
import type { ApplicationExtension, CreationInput, ExtensionContext } from '../services/extension-registry.js';

/** Alphanumeric secret safe to drop into config files and connection URIs. */
function generatePassword(len = 24): string {
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';
  const bytes = randomBytes(len);
  let out = '';
  for (let i = 0; i < len; i++) out += alphabet[bytes[i]! % alphabet.length];
  return out;
}

/** Standalone Redis build for Windows (maintained fork; ships redis-server.exe). */
const REDIS_WINDOWS_URL =
  'https://github.com/tporadowski/redis/releases/download/v5.0.14.1/Redis-x64-5.0.14.1.zip';

export interface DbConnectionInfo {
  engine: 'redis' | 'postgres' | 'mysql';
  host: string;
  port: number;
  username: string | null;
  password: string;
  database: string | null;
  uri: string;
}

/* ------------------------------------------------------------------ */
/* Redis                                                               */
/* ------------------------------------------------------------------ */

const RedisCreateConfig = z.object({
  maxMemoryMb: z.number().int().min(16).max(262144).optional(),
});

function redisConf(port: number, password: string, maxMemoryMb?: number): string {
  const lines = [
    '# Generated by ChickenPanel',
    'bind 0.0.0.0',
    `port ${port}`,
    `requirepass ${password}`,
    'dir ./data',
    'appendonly yes',
    'protected-mode yes',
  ];
  if (maxMemoryMb) {
    lines.push(`maxmemory ${maxMemoryMb}mb`, 'maxmemory-policy allkeys-lru');
  }
  return lines.join('\n') + '\n';
}

const redisExtension: ApplicationExtension = {
  type: 'redis',
  displayName: 'Redis',
  description: 'Managed Redis key-value store with an auto-generated password. Downloads a standalone Redis on Windows.',
  configSchema: RedisCreateConfig,
  async buildCreation(input: CreationInput, ctx: ExtensionContext) {
    const cfg = RedisCreateConfig.parse(input.config);
    const [port] = await ctx.allocatePorts(input.nodeId, 1);
    if (!port) throw new Error('Port allocation failed');
    const password = generatePassword();
    const isWindows = input.node.platform === 'win32';

    const steps: ProvisionStep[] = [
      { op: 'mkdir', path: 'data' },
      { op: 'write', path: 'redis.conf', content: redisConf(port, password, cfg.maxMemoryMb), base64: false },
    ];
    let startCommand: string[];
    if (isWindows) {
      steps.push(
        { op: 'download', url: REDIS_WINDOWS_URL, dest: '_engine/redis.zip' },
        { op: 'extract', archive: '_engine/redis.zip', dest: 'engine' },
      );
      // Backslash path so cmd.exe does not treat the "/" as a switch delimiter.
      startCommand = ['engine\\redis-server.exe', 'redis.conf'];
    } else {
      // Uses redis-server from the node's PATH (install via your package manager).
      startCommand = ['redis-server', 'redis.conf'];
    }

    const connection: DbConnectionInfo = {
      engine: 'redis',
      host: '127.0.0.1',
      port,
      username: null,
      password,
      database: null,
      uri: `redis://:${password}@HOST:${port}`,
    };
    const config = { engine: 'redis', port, password, maxMemoryMb: cfg.maxMemoryMb ?? null, startCommand, connection };

    return {
      spec: dbSpec(input, 'redis', startCommand, port, { type: 'stdin', command: 'shutdown nosave' }),
      steps,
      ports: [port],
      config,
      env: input.env,
    };
  },
  buildRuntimeSpec: (app) => dbRuntimeSpec(app, { type: 'stdin', command: 'shutdown nosave' }),
};

/* ------------------------------------------------------------------ */
/* PostgreSQL (uses the node's PostgreSQL binaries if present)         */
/* ------------------------------------------------------------------ */

const PostgresCreateConfig = z.object({
  database: z
    .string()
    .regex(/^[a-zA-Z][a-zA-Z0-9_]{0,62}$/, 'Database name must start with a letter')
    .default('appdb'),
});

const postgresExtension: ApplicationExtension = {
  type: 'postgres',
  displayName: 'PostgreSQL',
  description:
    'Managed PostgreSQL with generated credentials. Requires the PostgreSQL server binaries (initdb/postgres) on the node, or Docker.',
  configSchema: PostgresCreateConfig,
  async buildCreation(input: CreationInput, ctx: ExtensionContext) {
    const cfg = PostgresCreateConfig.parse(input.config);
    const [port] = await ctx.allocatePorts(input.nodeId, 1);
    if (!port) throw new Error('Port allocation failed');
    const password = generatePassword();
    const username = 'chicken';

    // initdb reads the superuser password from a file, which we then remove.
    const steps: ProvisionStep[] = [
      { op: 'write', path: '.pgpw', content: password, base64: false },
      {
        op: 'exec',
        command: ['initdb', '-D', 'data', '-U', username, '-A', 'scram-sha-256', '--pwfile=.pgpw', '-E', 'UTF8'],
        cwd: '.',
        timeoutMs: 300000,
      },
      { op: 'exec', command: ['node', '-e', 'require("fs").rmSync(".pgpw",{force:true})'], cwd: '.', timeoutMs: 30000 },
    ];
    const startCommand = ['postgres', '-D', 'data', '-p', String(port), '-c', 'listen_addresses=*'];

    const connection: DbConnectionInfo = {
      engine: 'postgres',
      host: '127.0.0.1',
      port,
      username,
      password,
      database: 'postgres',
      uri: `postgresql://${username}:${password}@HOST:${port}/postgres`,
    };
    const config = { engine: 'postgres', port, username, password, database: cfg.database, startCommand, connection };

    return {
      spec: dbSpec(input, 'postgres', startCommand, port, { type: 'signal', signal: 'SIGINT' }),
      steps,
      ports: [port],
      config,
      env: input.env,
    };
  },
  buildRuntimeSpec: (app) => dbRuntimeSpec(app, { type: 'signal', signal: 'SIGINT' }),
};

/* ------------------------------------------------------------------ */
/* MySQL / MariaDB (uses the node's mysqld/mariadbd if present)        */
/* ------------------------------------------------------------------ */

const MysqlCreateConfig = z.object({});

const mysqlExtension: ApplicationExtension = {
  type: 'mysql',
  displayName: 'MySQL / MariaDB',
  description:
    'Managed MySQL/MariaDB with a generated root password. Requires the MySQL or MariaDB server binaries (mysqld) on the node, or Docker.',
  configSchema: MysqlCreateConfig,
  async buildCreation(input: CreationInput, ctx: ExtensionContext) {
    const [port] = await ctx.allocatePorts(input.nodeId, 1);
    if (!port) throw new Error('Port allocation failed');
    const password = generatePassword();

    const steps: ProvisionStep[] = [
      { op: 'mkdir', path: 'data' },
      {
        op: 'exec',
        command: ['mysqld', '--initialize-insecure', '--datadir=data'],
        cwd: '.',
        timeoutMs: 300000,
      },
    ];
    // Note: root starts passwordless after --initialize-insecure; the password
    // is applied on first boot via init-file.
    const initSql = `ALTER USER 'root'@'localhost' IDENTIFIED BY '${password}';\nCREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '${password}';\nGRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;\nFLUSH PRIVILEGES;\n`;
    steps.push({ op: 'write', path: 'init.sql', content: initSql, base64: false });
    const startCommand = ['mysqld', '--datadir=data', `--port=${port}`, '--bind-address=0.0.0.0', '--init-file=init.sql'];

    const connection: DbConnectionInfo = {
      engine: 'mysql',
      host: '127.0.0.1',
      port,
      username: 'root',
      password,
      database: null,
      uri: `mysql://root:${password}@HOST:${port}`,
    };
    const config = { engine: 'mysql', port, username: 'root', password, startCommand, connection };

    return {
      spec: dbSpec(input, 'mysql', startCommand, port, { type: 'signal', signal: 'SIGTERM' }),
      steps,
      ports: [port],
      config,
      env: input.env,
    };
  },
  buildRuntimeSpec: (app) => dbRuntimeSpec(app, { type: 'signal', signal: 'SIGTERM' }),
};

/* ------------------------------------------------------------------ */
/* Shared spec builders                                                */
/* ------------------------------------------------------------------ */

function dbSpec(
  input: CreationInput,
  type: string,
  startCommand: string[],
  port: number,
  stopMethod: AppRuntimeSpec['stopMethod'],
): AppRuntimeSpec {
  return {
    appId: 'pending',
    name: input.name,
    type,
    startCommand,
    stopMethod,
    stopGraceSeconds: 30,
    env: input.env,
    restartPolicy: input.restartPolicy,
    limits: {
      cpuPercent: input.limits.cpuPercent ?? null,
      memoryMb: input.limits.memoryMb ?? null,
      diskMb: input.limits.diskMb ?? null,
    },
    ports: [port],
  };
}

function dbRuntimeSpec(app: Application, stopMethod: AppRuntimeSpec['stopMethod']): AppRuntimeSpec {
  const cfg = app.config as { startCommand?: string[] };
  const startCommand = Array.isArray(cfg.startCommand) && cfg.startCommand.length > 0 ? cfg.startCommand : ['true'];
  return {
    appId: app.id,
    name: app.name,
    type: app.type,
    startCommand,
    stopMethod,
    stopGraceSeconds: 30,
    env: (app.env as Record<string, string>) ?? {},
    restartPolicy: app.restartPolicy as never,
    limits: (app.limits as never) ?? { cpuPercent: null, memoryMb: null, diskMb: null },
    ports: app.ports,
  };
}

export const databaseExtensions = [redisExtension, postgresExtension, mysqlExtension];
