import { z } from 'zod';
import type { AppRuntimeSpec, ProvisionStep } from '@nexpanel/shared';
import { getMinecraftCatalog, softwareProviders } from './catalog.js';

export * from './catalog.js';

export const MinecraftConfigSchema = z.object({
  software: z.enum(['vanilla', 'paper']).default('paper'),
  version: z.string().min(1).max(32),
  memoryMb: z.number().int().min(512).max(262144).default(4096),
  difficulty: z.enum(['peaceful', 'easy', 'normal', 'hard']).default('normal'),
  gamemode: z.enum(['survival', 'creative', 'adventure', 'spectator']).default('survival'),
  viewDistance: z.number().int().min(2).max(32).default(10),
  simulationDistance: z.number().int().min(2).max(32).default(10),
  maxPlayers: z.number().int().min(1).max(1000).default(20),
  motd: z.string().max(150).optional(),
  autoStart: z.boolean().default(false),
  /** Preferred port; the allocator falls back automatically if taken. */
  preferredPort: z.number().int().min(1024).max(65535).optional(),
  /** Explicit consent to the Minecraft EULA (https://aka.ms/MinecraftEULA). */
  eulaAccepted: z.boolean().default(false),
});
export type MinecraftConfig = z.infer<typeof MinecraftConfigSchema>;

export function buildServerProperties(cfg: MinecraftConfig, port: number, name: string): string {
  const props: Record<string, string | number | boolean> = {
    'server-port': port,
    'query.port': port,
    motd: cfg.motd ?? `${name} — powered by ChickenPanel`,
    difficulty: cfg.difficulty,
    gamemode: cfg.gamemode,
    'view-distance': cfg.viewDistance,
    'simulation-distance': cfg.simulationDistance,
    'max-players': cfg.maxPlayers,
    'enable-query': false,
    'online-mode': true,
    'white-list': false,
    'spawn-protection': 16,
  };
  return (
    '# Generated by ChickenPanel\n' +
    Object.entries(props)
      .map(([k, v]) => `${k}=${v}`)
      .join('\n') +
    '\n'
  );
}

export function buildStartCommand(cfg: MinecraftConfig): string[] {
  const mem = cfg.memoryMb;
  const flags = [
    `-Xms${Math.min(mem, Math.max(512, Math.floor(mem / 2)))}M`,
    `-Xmx${mem}M`,
    // Aikar-style flags, safe for both vanilla and Paper
    '-XX:+UseG1GC',
    '-XX:+ParallelRefProcEnabled',
    '-XX:MaxGCPauseMillis=200',
    '-XX:+UnlockExperimentalVMOptions',
    '-XX:+DisableExplicitGC',
  ];
  return ['java', ...flags, '-jar', 'server.jar', '--nogui'];
}

export interface MinecraftCreationPlan {
  spec: Omit<AppRuntimeSpec, 'appId'>;
  steps: ProvisionStep[];
  port: number;
}

/**
 * Compile a Minecraft server creation into generic agent provisioning steps.
 * The port must already be allocated by the caller.
 */
export async function buildMinecraftProvisioning(
  name: string,
  cfg: MinecraftConfig,
  port: number,
  env: Record<string, string>,
  restartPolicy: 'never' | 'on-crash' | 'always',
): Promise<MinecraftCreationPlan> {
  const provider = softwareProviders[cfg.software];
  if (!provider) throw new Error(`Unsupported software: ${cfg.software}`);
  const jar = await provider.resolveJar(cfg.version);

  const steps: ProvisionStep[] = [
    { op: 'download', url: jar.url, dest: 'server.jar', ...(jar.sha256 ? { sha256: jar.sha256 } : {}) },
    {
      op: 'write',
      path: 'eula.txt',
      // Only written as accepted when the user explicitly consented in the UI.
      content: cfg.eulaAccepted
        ? '# Accepted by the server owner via ChickenPanel\neula=true\n'
        : '# You must accept the Minecraft EULA (https://aka.ms/MinecraftEULA)\neula=false\n',
      base64: false,
    },
    { op: 'write', path: 'server.properties', content: buildServerProperties(cfg, port, name), base64: false },
    ...(provider.supportsPlugins ? [{ op: 'mkdir' as const, path: 'plugins' }] : []),
  ];

  return {
    spec: {
      name,
      type: 'minecraft',
      startCommand: buildStartCommand(cfg),
      stopMethod: { type: 'stdin', command: 'stop' },
      stopGraceSeconds: 60,
      env,
      restartPolicy,
      limits: { cpuPercent: null, memoryMb: cfg.memoryMb + 1024, diskMb: null },
      ports: [port],
    },
    steps,
    port,
  };
}

export { getMinecraftCatalog };
